SUBROUTINE ALLOCATE_GAS
!
USE GAS
USE CALC
!
IMPLICIT NONE
!
INTEGER :: ERROR



ALLOCATE (FSP(MSP),SP(5,MSP),SPR(3,MSP),SPM(10,MSP,MSP),&
   &ISPR(2,MSP),ISPV(MSP),VMP(MSP),CR(MSP),TCOL(MSP,MSP),STAT=ERROR)
!
IF (ERROR /= 0) THEN
  WRITE (*,*)'PROGRAM COULD NOT ALLOCATE SPECIES VARIABLES',ERROR
END IF
!
IF (MMVM > 0) THEN

  ALLOCATE (SPVM(4,MMVM,MSP),ISPVM(2,MMVM,MSP),STAT=ERROR)
  IF (ERROR /= 0) THEN
    WRITE (*,*)'PROGRAM COULD NOT ALLOCATE VIBRATION VARIABLES',ERROR
  END IF
END IF

RETURN
END SUBROUTINE ALLOCATE_GAS