      SUBROUTINE EXTEND_MNM(FAC)
      !
      !--the maximum number of molecules is increased to FAC*NM
      !
      USE MOLECS
      USE CALC
      USE GAS
      !
      IMPLICIT NONE
      !
      INTEGER :: I,J,MNMN,ERROR
      REAL*8 :: FAC     
      REAL*8,DIMENSION(:),ALLOCATABLE :: PXB,PYB,PTIMB,PROTB
      REAL*8,DIMENSION(:,:),ALLOCATABLE :: PVB
      INTEGER,DIMENSION(:),ALLOCATABLE :: IPSPB,IPCCELLB,ICREFB
      INTEGER,DIMENSION(:,:),ALLOCATABLE :: IPVIBB
      !defined in module: EXTEND_MNM_LINK
      
      MNMN=CEILING(MNM*FAC)

      ALLOCATE(PXB(MNM)) ;    PXB=PX
      DEALLOCATE(PX); ALLOCATE(PX(MNMN))
      PX(1:MNM)=PXB ; PX(MNM+1:MNMN)=0.0D00
      DEALLOCATE(PXB)
      
      ALLOCATE(PYB(MNM)) ;    PYB=PY
      DEALLOCATE(PY); ALLOCATE(PY(MNMN))
      PY(1:MNM)=PYB ; PY(MNM+1:MNMN)=0.0D00
      DEALLOCATE(PYB)
      
      IF(MMRM .GT. 0)THEN
         ALLOCATE(PROTB(MNM)) ;    PROTB=PROT
         DEALLOCATE(PROT); ALLOCATE(PROT(MNMN))
         PROT(1:MNM)=PROTB ; PROT(MNM+1:MNMN)=0.0D00
         DEALLOCATE(PROTB)
      END IF

      ALLOCATE(PTIMB(MNM)) ;    PTIMB=PTIM
      DEALLOCATE(PTIM); ALLOCATE(PTIM(MNMN))
      PTIM(1:MNM)=PTIMB ; PTIM(MNM+1:MNMN)=0.0D00
      DEALLOCATE(PTIMB)
      
      ALLOCATE(PVB(3,MNM)) ;    PVB=PV
      DEALLOCATE(PV); ALLOCATE(PV(3,MNMN))
      PV(:,1:MNM)=PVB ; PV(:,MNM+1:MNMN)=0.0D00
      DEALLOCATE(PVB)
      
      ALLOCATE(IPSPB(MNM)) ;    IPSPB=IPSP
      DEALLOCATE(IPSP); ALLOCATE(IPSP(MNMN))
      IPSP(1:MNM)=IPSPB ; IPSP(MNM+1:MNMN)=0
      DEALLOCATE(IPSPB)
      
      ALLOCATE(ICREFB(MNM)) ;    ICREFB=ICREF
      DEALLOCATE(ICREF); ALLOCATE(ICREF(MNMN))      
      ICREF(1:MNM)=ICREFB ; ICREF(MNM+1:MNMN)=0
      DEALLOCATE(ICREFB)
      
      ALLOCATE(IPCCELLB(MNM)) ;    IPCCELLB=IPCCELL
      DEALLOCATE(IPCCELL); ALLOCATE(IPCCELL(MNMN))
      IPCCELL(1:MNM)=IPCCELLB ; IPCCELL(MNM+1:MNMN)=0
      DEALLOCATE(IPCCELLB)
      
      IF(MMVM .GT. 0)THEN
         ALLOCATE(IPVIBB(MMVM,MNM)) ;    IPVIBB=IPVIB
         DEALLOCATE(IPVIB); ALLOCATE(IPVIB(MMVM,MNMN))
         IPVIB(:,1:MNM)=IPVIBB ; IPVIB(:,MNM+1:MNMN)=0
         DEALLOCATE(IPVIBB)
      END IF

      MNM=MNMN
      RETURN
      END SUBROUTINE EXTEND_MNM