   SUBROUTINE INITIALISE_SAMPLES(N)
   !
   USE SAMPLES
   USE CALC
   USE MOLECS
   USE CELLINFO
   USE GAS
   IMPLICIT NONE
   INTEGER :: N
   IF(N .EQ. 0)THEN
      ALLOCATE(CSS(7,NBEDGES(5),MSP,2),CSSS(6,NBEDGES(5)),&
         &CS(8+MMVM,NCELLS,MSP),COLLS(NCELLS),CLSEP(NCELLS),EMOLS(NCELLS))
   END IF
   NSAMP=0
   TISAMP=FTIME
   COLLS=0.0D00 ; CLSEP=0.0D00 ; EMOLS=0.0D00
   CS=0.0D00 ; CSS=0.0D00 ; CSSS=0.0D00
   TCOL=0.0D00
   !
   END SUBROUTINE INITIALISE_SAMPLES