SUBROUTINE READ_RESTART
USE NODEINFO
USE CELLINFO
USE BOUNDINFO
USE CALC
USE GAS
USE MOLECS
USE SAMPLES
IMPLICIT NONE

   
OPEN (7,FILE='parameters.bin',FORM='UNFORMATTED',ACCESS="SEQUENTIAL")
READ(7) NNODES,NCELLS,NCCELLS,NBEDGES,NBOUND,NWALL,GASCODE,MNM
CLOSE(7)

OPEN(7,FILE='restart.bin',FORM='UNFORMATTED',ACCESS="SEQUENTIAL")

!GAS INFO
SELECT CASE (GASCODE)
CASE(1)
   CALL HARD_SPHERE
CASE(2)
   CALL ARGON
CASE(3)
   CALL IDEAL_NITROGEN
CASE(5)
   CALL IDEAL_AIR
CASE(4)
   CALL REAL_NITROGEN
   CASE DEFAULT
   WRITE(*,*) "UNSUPPORTTED GAS"
   STOP
END SELECT



ALLOCATE( ENTR(6,MSP,NBEDGES(2)+NBEDGES(3)))

!NODE INFO
ALLOCATE(NODES(2,NNODES))

!CELL INFO
ALLOCATE(ICELL(11,NCELLS),ICCELL(3,NCCELLS),IS(4,NCELLS),CELL(1,NCELLS),CCELL(5,NCCELLS))

ALLOCATE(SSEG(5,NBEDGES(5)),SSSEG(9,MSP,NBEDGES(5)),SSSEG_INT(9,MSP),SSEG_INT(5,NWALL))

ALLOCATE(ENTRYIN(2,NBEDGES(2)),ENTRYOUT(2,NBEDGES(3)))

ALLOCATE(SURFACEVEC(2,NBEDGES(5)))

ALLOCATE(IBEDGE1(2,NBEDGES(2)),IBEDGE2(2,NBEDGES(3)),IBEDGE3(2,NBEDGES(4)),IBEDGE4(2,NBEDGES(5)))

!BOUND INFO
ALLOCATE(IWBOUND(NBOUND),IWALL(0:NBEDGES(5),NWALL))

!CALC 


!MOLECS
IF (MMVM > 0) THEN
   ALLOCATE (PX(MNM),PY(MNM),PTIM(MNM),PROT(MNM),PV(3,MNM),IPSP(MNM),&
      &IPCCELL(MNM),ICREF(MNM),IPVIB(MMVM,MNM))
ELSE
   IF (MMRM > 0) THEN
      ALLOCATE (PX(MNM),PY(MNM),PTIM(MNM),PROT(MNM),PV(3,MNM),IPSP(MNM),&
         &IPCCELL(MNM),ICREF(MNM))
   ELSE
      ALLOCATE (PX(MNM),PY(MNM),PTIM(MNM),PV(3,MNM),IPSP(MNM),&
      &IPCCELL(MNM),ICREF(MNM))
   END IF
END IF
   
!SAMPLE

 ALLOCATE(CSS(7,NBEDGES(5),MSP,2),CSSS(6,NBEDGES(5)),CS(8+MMVM,NCELLS,MSP),&
    &COLLS(NCELLS),CLSEP(NCELLS),EMOLS(NCELLS))
   
   

!NODEINFO AND BOUN INFO
READ(7) NODES,ICELL,ICCELL,IS,CELL,CCELL,SSEG,SSSEG,SSEG_INT,SSSEG_INT,&
         &ENTRYIN,ENTRYOUT,SURFACEVEC,IBEDGE1,IBEDGE2,IBEDGE3,IBEDGE4,MAXCELL,MINCELL
READ(7) IWBOUND,IWALL

!CALC
READ(7) MOLSC,IMTS,NNC,ISF,ICENS,FNUM,DTM,CPDTM,TPDTM,SAMPRAT,OUTRAT,&
        &TSAMP,TOUT,DTSAMP,DTOUT,FTIME,TLIM,TOTMOV,TOTCOL,TOTCOLI,&
        &TOTMOVI,ENTMASS,TCOL



!GAS
READ(7) RMAS,CXSS,RGFS,VMPM,FPR,FMA,FP,CTM,FND,FTMP,FVTMP,VFX,VFY,&
        &CR,FSP,VMP,SP,SPR,SPM
IF(MMVM .GT. 0)THEN
   READ(7) SPVM
END IF
READ(7) ENTR,ISPV,ISPR
IF(MMVM .GT. 0)THEN
   READ(7) ISPVM
END IF

!MOLECS

READ(7) NM,PX,PY,PTIM,PV,IPSP,IPCCELL,ICREF

IF( MMRM>0 )THEN
   READ(7) PROT
   IF(MMVM >0)  READ(7) IPVIB
   END IF

!SAMPLE
   
READ(7) NSAMP,TISAMP,EMOLS,CSSS,CS,CSS,COLLS,CLSEP
CLOSE(7)
END SUBROUTINE
