SUBROUTINE WRITE_RESTART
USE NODEINFO
USE CELLINFO
USE BOUNDINFO
USE CALC
USE GAS
USE MOLECS
USE SAMPLES
IMPLICIT NONE

   
OPEN(7,FILE='parameters.bin',FORM='UNFORMATTED',ACCESS="SEQUENTIAL")
WRITE(7) NNODES,NCELLS,NCCELLS,NBEDGES,NBOUND,NWALL,GASCODE,MNM
CLOSE(7)

OPEN(7,FILE='restart.bin',FORM='UNFORMATTED',ACCESS="SEQUENTIAL")
!NODEINFO AND BOUN INFO
WRITE(7) NODES,ICELL,ICCELL,IS,CELL,CCELL,SSEG,SSSEG,SSEG_INT,SSSEG_INT,&
         &ENTRYIN,ENTRYOUT,SURFACEVEC,IBEDGE1,IBEDGE2,IBEDGE3,IBEDGE4,MAXCELL,MINCELL
WRITE(7) IWBOUND,IWALL

!CALC
WRITE(7) MOLSC,IMTS,NNC,ISF,ICENS,FNUM,DTM,CPDTM,TPDTM,SAMPRAT,OUTRAT,&
        &TSAMP,TOUT,DTSAMP,DTOUT,FTIME,TLIM,TOTMOV,TOTCOL,TOTCOLI,&
        &TOTMOVI,ENTMASS,TCOL

!GAS
WRITE(7) RMAS,CXSS,RGFS,VMPM,FPR,FMA,FP,CTM,FND,FTMP,FVTMP,VFX,VFY,&
        &CR,FSP,VMP,SP,SPR,SPM
IF(MMVM .GT. 0)THEN
   WRITE(7) SPVM
END IF
WRITE(7) ENTR,ISPV,ISPR
IF(MMVM .GT. 0)THEN
   WRITE(7) ISPVM
END IF
!MOLECS

WRITE(7) NM,PX,PY,PTIM,PV,IPSP,IPCCELL,ICREF

IF( MMRM>0 )THEN
   WRITE(7) PROT
   IF(MMVM >0)  WRITE(7) IPVIB
   END IF

!SAMPLE
   
WRITE(7) NSAMP,TISAMP,EMOLS,CSSS,CS,CSS,COLLS,CLSEP
CLOSE(7)
END SUBROUTINE WRITE_RESTART